### ISSUE TITLE
Issue when running the python draftvid.py command

### ISSUE THREAD

**Issue by tigersfan102720** [thedaynos/fantasyDraftHighlights#1]
Here's the error:

python draftvid.py
Traceback (most recent call last):
  File "draftvid.py", line 49, in <module>
    draftDriver=webdriver.Chrome(chrome_options=draftOptions)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Not really sure how I'm supposed to see the video. Is a chrome browser supposed to open? I do that command and nothing happens. No video, no sleeper site.

**Comment by thedaynos** [comment]
The error message says: 
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. 
What that tells me is that you don't have the webdriver in the correct directory.  I can help you with that. 
What OS are you running?

**Comment by thedaynos** [comment]
Also 2 more things...

I see you're using python 2.7 and I wrote this in python 3.* .  There are some pieces of this code that need python 3.* to run.  Please run this in 3. 

To answer your question on how you're supposed to view the highlights.  There are 2 ways.  The first is to use selenium to pull up youtube on the computer that's running the app.   That's why you need that chromedriver. 
The 2nd way would be to use chromecast.  If you are using sleeperbot for your draft AND chromecast to 
view the highlights, then you don't need to worry about selenium.  

Please check the install/readme again and re-download the files. I've made quite a few very useful updates last night!  Also install python3!

**Comment by tigersfan102720** [comment]
Will running the code python3 work instead? I have python3 installed but I believe the default is to run in 2 for me. 

Here's my OS version: Mac OS Mojave 10.14.5

Now I get an issue with selenium when running the code: python3 draftvid.py

Austins-MacBook-Pro:FantasyDraft Austin$ python3 draftvid.py
Traceback (most recent call last):
  File "draftvid.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Austins-MacBook-Pro:FantasyDraft Austin$ 

I installed selenium via pip install selenium after dragging the FantasyDraft folder into terminal for the directory. That is the directory I have been using and how I am doing it. I appreciate your response a lot, this has been stressing me out since I'm not all that familiar with Python. 

Should I erase everything, download that folder with all the stuff, and then drag that folder into terminal for the directory and install selenium/chromium during that time?

**Comment by thedaynos** [comment]
I have never used a mac for python so I'm sorry I can't be of much help here aside from... yes if this is the only python app you're running, I suggest you blow everything else out and re-install python3. Most likely you have multiple versions of python on your computer and for some reason when you're doing "pip install", the install is going to the other version than what you're running on. I've seen that on my ubuntu machine before.  Best bet is just to blow out python2 somehow if you don't need that for anything else.

**Comment by tigersfan102720** [comment]
I reinstalled everything and got it to only load onto Python 3, but it gives me the exact same error. Do you extract the Chromedriver into the fantasy folder? That's what I did and it still says it's not in the right path. 

<img width="634" alt="Screenshot at Jul 20 19-40-21" src="https://user-images.githubusercontent.com/46800543/61585326-8df10280-ab26-11e9-9bc8-a63e2dfa1551.png">
<img width="587" alt="Fantasy" src="https://user-images.githubusercontent.com/46800543/61585329-a3662c80-ab26-11e9-90fb-a3f8ff1b9405.png">

Also when I enter the command, this pops up for a millisecond. 
<img width="428" alt="Screenshot at Jul 20 19-46-01" src="https://user-images.githubusercontent.com/46800543/61585347-3901bc00-ab27-11e9-8f4b-3d1072973555.png">

**Comment by thedaynos** [comment]
ok yeah what's happening is that the chromedriver is not being found by selenium.  Not a big deal.  Just copy/paste that chromedriver into one of your PATH directories.  I really am Mac illiterate so I'm not sure exactly what directories that would be, but if you do a couple google searches regarding setting PATH on mac os, it should be easy to figure out.  Once it's in there then selenium will find the chromedriver.

Also for that last box, just click allow.
